// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/myapis/speech.proto

package org.grpc.speech;

public interface SpeechRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:speechService.SpeechRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes message = 1;</code>
   */
  com.google.protobuf.ByteString getMessage();
}
